[package]
name = "olive-core"
description = "Fallible re-port of Rust's `core`: foundational traits, allocation errors, and panic machinery."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
olive-macros = { workspace = true }
allocator-api2 = { workspace = true }

[build-dependencies]
olive-build = { workspace = true }

[lints]
workspace = true
