//! Comparison impls for [`String`](super::String).
//!
//! Same-type impls (`PartialEq`, `Eq`, `PartialOrd`, `Ord`) are
//! written directly below. Cross-type impls are generated by `impl_cmp!`;
//! each body annotates both operands as `&str` before delegating to `str`'s
//! comparison, so the nothing else ever participates in the result.

// ─── Same-type impls ──────────────────────────────────────────────────────────

use super::String;
use crate::borrow::Cow;
use crate::boxed::Box;
use core::{cmp::Ordering, ops::Deref};
use olive_core::alloc::Allocator;

impl<A: Allocator> PartialEq for String<A> {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        self.deref() == other.deref()
    }
}

impl<A: Allocator> Eq for String<A> {}

impl<A: Allocator> PartialOrd for String<A> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl<A: Allocator> Ord for String<A> {
    #[inline]
    fn cmp(&self, other: &Self) -> Ordering {
        self.deref().cmp(other.deref())
    }
}

// ─── Cross-type impls (macro-generated) ───────────────────────────────────────

/// Emits four cross-type impls: `PartialEq<RHS> for LHS`, `PartialEq<LHS> for
/// RHS`, `PartialOrd<RHS> for LHS`, and `PartialOrd<LHS> for RHS`. Each body
/// pins both operands to `$prim` (always `str`) via an explicit type annotation
/// before delegating, so the result depends only on string content.
///
/// Usage: `impl_cmp!((generic_params), LhsTy, RhsTy, PrimTy);`
/// where `(generic_params)` is the exact token list for the `impl<…>` header.
macro_rules! impl_cmp {
    (($($generics:tt)*), $lhs:ty, $rhs:ty, $prim:ty) => {
        #[allow(unused_lifetimes)]
        impl<$($generics)*> core::cmp::PartialEq<$rhs> for $lhs {
            #[inline]
            fn eq(&self, other: &$rhs) -> bool {
                let lhs: &$prim = self;
                let rhs: &$prim = other;
                core::cmp::PartialEq::eq(lhs, rhs)
            }
        }

        #[allow(unused_lifetimes)]
        impl<$($generics)*> core::cmp::PartialEq<$lhs> for $rhs {
            #[inline]
            fn eq(&self, other: &$lhs) -> bool {
                let lhs: &$prim = self;
                let rhs: &$prim = other;
                core::cmp::PartialEq::eq(lhs, rhs)
            }
        }

        #[allow(unused_lifetimes)]
        impl<$($generics)*> core::cmp::PartialOrd<$rhs> for $lhs {
            #[inline]
            fn partial_cmp(&self, other: &$rhs) -> Option<core::cmp::Ordering> {
                let lhs: &$prim = self;
                let rhs: &$prim = other;
                core::cmp::PartialOrd::partial_cmp(lhs, rhs)
            }
        }

        #[allow(unused_lifetimes)]
        impl<$($generics)*> core::cmp::PartialOrd<$lhs> for $rhs {
            #[inline]
            fn partial_cmp(&self, other: &$lhs) -> Option<core::cmp::Ordering> {
                let lhs: &$prim = self;
                let rhs: &$prim = other;
                core::cmp::PartialOrd::partial_cmp(lhs, rhs)
            }
        }
    };
}

// String<A> vs non-Cow targets.
// String <-> str
impl_cmp!((A: Allocator), String<A>, str, str);
// String <-> &str
impl_cmp!(('ref_b, A: Allocator), String<A>, &'ref_b str, str);
// Additional implementation: String <-> Box<str>
impl_cmp!((A: Allocator, B: Allocator), String<A>, Box<str, B>, str);
// Additional implementation: String <-> &Box<str>
impl_cmp!(('ref_b, A: Allocator, B: Allocator), String<A>, &'ref_b Box<str, B>, str);
// Additional implementation: Box<str> <-> str
impl_cmp!((A: Allocator), Box<str, A>, str, str);
// Additional implementation: &str <-> Box<str>
impl_cmp!(('ref_a, B: Allocator), &'ref_a str, Box<str, B>, str);

// Cow<'a, str> vs non-Cow targets.
// Cow<str> <-> str
impl_cmp!(('a), Cow<'a, str>, str, str);
// Cow<str> <-> &str
impl_cmp!(('a, 'ref_b), Cow<'a, str>, &'ref_b str, str);
// Additional implementation: Cow<str> <-> Box<str>
impl_cmp!(('a, B: Allocator), Cow<'a, str>, Box<str, B>, str);
// Additional implementation: Cow<str> <-> &Box<str>
impl_cmp!(('a, 'ref_b, B: Allocator), Cow<'a, str>, &'ref_b Box<str, B>, str);
// Cow<str> <-> String
impl_cmp!(('a, B: Allocator), Cow<'a, str>, String<B>, str);

// ─── Exhaustive network tests (maybe) ─────────────────────────────────────────────────
//
// Six representations form a complete graph K₆ with C(6,2) = 15 edges:
//   V₀ = str          (unsized; handled via &str in practice)
//   V₁ = &str         (shared reference)
//   V₂ = Box<str>     (heap-owned, global allocator)
//   V₃ = String       (= String<Global>)
//   V₄ = Cow::Borrowed<str>
//   V₅ = Cow::Owned<str>
//
// Three invariant batches are verified per edge:
//   Batch 1 – Equal values:  eq symmetric, reflexive, A-B-A transitivity, partial_cmp == Equal.
//   Batch 2 – Unequal values: neq symmetric, ¬eq ⇔ neq, partial_cmp ≠ Equal.
//   Batch 3 – Strictly increasing triple: transitivity + duality of ordering.

#[cfg(test)]
mod tests {
    extern crate std;
    use crate::borrow::Cow;
    use crate::boxed::Box;
    use crate::string::String;
    use core::cmp::Ordering;

    /// Shorthand: build a `String<Global>` from a literal.
    fn mk(s: &str) -> String {
        String::try_from_str(s).unwrap()
    }

    /// Shorthand: build a `Box<str>` from a literal.
    fn box_mk(s: &str) -> Box<str> {
        Box::try_clone_from_ref(s).unwrap()
    }

    // ───────────────────────────────────────────────────────────────────────
    // BATCH 1: Equal-value consistency
    // For each edge (X, Y) with X and Y holding the same content:
    //   • X == Y and Y == X (symmetry)
    //   • X == X and Y == Y (reflexivity at each endpoint)
    //   • X.partial_cmp(Y) == Some(Equal) and Y.partial_cmp(X) == Some(Equal)
    // ───────────────────────────────────────────────────────────────────────

    mod batch1_equal {
        use super::*;

        // Multibyte UTF-8: é (U+00E9, 2 bytes), ö (U+00F6, 2 bytes),
        // 🌍 (U+1F30D, 4-byte astral), 😀 (U+1F600, 4-byte astral).
        // Exercises byte-boundary alignment across all representations.
        const VAL: &str = "héllo wörld 🌍\u{1F600}";

        /// Edge 0-1: str vs &str
        #[test]
        fn e01_str_vs_ref_str() {
            let s: &str = VAL;
            assert_eq!(s, s); // reflexive
            assert_eq!(VAL, s); // symmetry (both are &str after coercion)
            assert_eq!(s.partial_cmp(VAL), Some(Ordering::Equal));
            assert_eq!(VAL.partial_cmp(s), Some(Ordering::Equal));
        }

        /// Edge 0-2: str vs Box<str>
        #[test]
        fn e02_str_vs_box_str() {
            let b = box_mk(VAL);
            assert_eq!(VAL, b);
            assert_eq!(b, VAL);
            assert_eq!(b, b); // reflexive on Box side
            assert_eq!(VAL, VAL); // reflexive on str side
            assert_eq!(VAL.partial_cmp(&b), Some(Ordering::Equal));
            assert_eq!(b.partial_cmp(VAL), Some(Ordering::Equal));
        }

        /// Edge 0-3: str vs String
        #[test]
        fn e03_str_vs_string() {
            let s = mk(VAL);
            assert_eq!(VAL, s);
            assert_eq!(s, VAL);
            assert_eq!(s, s);
            assert_eq!(VAL, VAL);
            assert_eq!(VAL.partial_cmp(&s), Some(Ordering::Equal));
            assert_eq!(s.partial_cmp(VAL), Some(Ordering::Equal));
        }

        /// Edge 0-4: str vs Cow::Borrowed
        #[test]
        fn e04_str_vs_cow_borrowed() {
            let c: Cow<str> = Cow::Borrowed(VAL);
            assert_eq!(VAL, c);
            assert_eq!(c, VAL);
            assert_eq!(c, c);
            assert_eq!(VAL, VAL);
            assert_eq!(VAL.partial_cmp(&c), Some(Ordering::Equal));
            assert_eq!(c.partial_cmp(VAL), Some(Ordering::Equal));
        }

        /// Edge 0-5: str vs Cow::Owned
        #[test]
        fn e05_str_vs_cow_owned() {
            let c: Cow<str> = Cow::Owned(mk(VAL));
            assert_eq!(VAL, c);
            assert_eq!(c, VAL);
            assert_eq!(c, c);
            assert_eq!(VAL, VAL);
            assert_eq!(VAL.partial_cmp(&c), Some(Ordering::Equal));
            assert_eq!(c.partial_cmp(VAL), Some(Ordering::Equal));
        }

        /// Edge 1-2: &str vs Box<str>
        #[test]
        fn e12_ref_str_vs_box_str() {
            let r: &str = VAL;
            let b = box_mk(VAL);
            assert_eq!(r, b);
            assert_eq!(b, r);
            assert_eq!(r, r);
            assert_eq!(b, b);
            assert_eq!(r.partial_cmp(&b), Some(Ordering::Equal));
            assert_eq!(b.partial_cmp(r), Some(Ordering::Equal));
        }

        /// Edge 1-3: &str vs String
        #[test]
        fn e13_ref_str_vs_string() {
            let r: &str = VAL;
            let s = mk(VAL);
            assert_eq!(r, s);
            assert_eq!(s, r);
            assert_eq!(r, r);
            assert_eq!(s, s);
            assert_eq!(r.partial_cmp(&s), Some(Ordering::Equal));
            assert_eq!(s.partial_cmp(r), Some(Ordering::Equal));
        }

        /// Edge 1-4: &str vs Cow::Borrowed
        #[test]
        fn e14_ref_str_vs_cow_borrowed() {
            let r: &str = VAL;
            let c: Cow<str> = Cow::Borrowed(VAL);
            assert_eq!(r, c);
            assert_eq!(c, r);
            assert_eq!(r, r);
            assert_eq!(c, c);
            assert_eq!(r.partial_cmp(&c), Some(Ordering::Equal));
            assert_eq!(c.partial_cmp(r), Some(Ordering::Equal));
        }

        /// Edge 1-5: &str vs Cow::Owned
        #[test]
        fn e15_ref_str_vs_cow_owned() {
            let r: &str = VAL;
            let c: Cow<str> = Cow::Owned(mk(VAL));
            assert_eq!(r, c);
            assert_eq!(c, r);
            assert_eq!(r, r);
            assert_eq!(c, c);
            assert_eq!(r.partial_cmp(&c), Some(Ordering::Equal));
            assert_eq!(c.partial_cmp(r), Some(Ordering::Equal));
        }

        /// Edge 2-3: Box<str> vs String
        #[test]
        fn e23_box_str_vs_string() {
            let b = box_mk(VAL);
            let s = mk(VAL);
            assert_eq!(b, s);
            assert_eq!(s, b);
            assert_eq!(b, b);
            assert_eq!(s, s);
            assert_eq!(b.partial_cmp(&s), Some(Ordering::Equal));
            assert_eq!(s.partial_cmp(&b), Some(Ordering::Equal));
        }

        /// Edge 2-4: Box<str> vs Cow::Borrowed
        #[test]
        fn e24_box_str_vs_cow_borrowed() {
            let b = box_mk(VAL);
            let c: Cow<str> = Cow::Borrowed(VAL);
            assert_eq!(b, c);
            assert_eq!(c, b);
            assert_eq!(b, b);
            assert_eq!(c, c);
            assert_eq!(b.partial_cmp(&c), Some(Ordering::Equal));
            assert_eq!(c.partial_cmp(&b), Some(Ordering::Equal));
        }

        /// Edge 2-5: Box<str> vs Cow::Owned
        #[test]
        fn e25_box_str_vs_cow_owned() {
            let b = box_mk(VAL);
            let c: Cow<str> = Cow::Owned(mk(VAL));
            assert_eq!(b, c);
            assert_eq!(c, b);
            assert_eq!(b, b);
            assert_eq!(c, c);
            assert_eq!(b.partial_cmp(&c), Some(Ordering::Equal));
            assert_eq!(c.partial_cmp(&b), Some(Ordering::Equal));
        }

        /// Edge 3-4: String vs Cow::Borrowed
        #[test]
        fn e34_string_vs_cow_borrowed() {
            let s = mk(VAL);
            let c: Cow<str> = Cow::Borrowed(VAL);
            assert_eq!(s, c);
            assert_eq!(c, s);
            assert_eq!(s, s);
            assert_eq!(c, c);
            assert_eq!(s.partial_cmp(&c), Some(Ordering::Equal));
            assert_eq!(c.partial_cmp(&s), Some(Ordering::Equal));
        }

        /// Edge 3-5: String vs Cow::Owned
        #[test]
        fn e35_string_vs_cow_owned() {
            let s = mk(VAL);
            let c: Cow<str> = Cow::Owned(mk(VAL));
            assert_eq!(s, c);
            assert_eq!(c, s);
            assert_eq!(s, s);
            assert_eq!(c, c);
            assert_eq!(s.partial_cmp(&c), Some(Ordering::Equal));
            assert_eq!(c.partial_cmp(&s), Some(Ordering::Equal));
        }

        /// Edge 4-5: Cow::Borrowed vs Cow::Owned
        #[test]
        fn e45_cow_borrowed_vs_cow_owned() {
            let cb: Cow<str> = Cow::Borrowed(VAL);
            let co: Cow<str> = Cow::Owned(mk(VAL));
            assert_eq!(cb, co);
            assert_eq!(co, cb);
            assert_eq!(cb, cb);
            assert_eq!(co, co);
            assert_eq!(cb.partial_cmp(&co), Some(Ordering::Equal));
            assert_eq!(co.partial_cmp(&cb), Some(Ordering::Equal));
        }
    }

    // ───────────────────────────────────────────────────────────────────────
    // BATCH 2: Unequal-value negative consistency
    // For each edge (X, Y) with X ≠ Y:
    //   • X != Y and Y != X (symmetry of inequality)
    //   • ¬(X == Y) and ¬(Y == X) (negation of equality)
    //   • X.partial_cmp(Y) != Some(Equal) and vice versa
    // ───────────────────────────────────────────────────────────────────────

    mod batch2_unequal {
        use super::*;

        // Both share prefix "caf" but differ at the last codepoint:
        //   é  = U+00E9 (2 bytes: C3 A9)
        //   ế  = U+1EBF (3 bytes: E1 BB BF)
        // Tests that comparison is by codepoint value, not byte length.
        const A: &str = "café";
        const B: &str = "caf\u{1EBF}";

        /// Edge 0-1: str vs &str
        #[test]
        fn e01_str_vs_ref_str() {
            let a: &str = A;
            let b: &str = B;
            assert_ne!(a, b);
            assert_ne!(b, a);
            assert!(!a.eq(b));
            assert!(!b.eq(a));
            assert_ne!(a.partial_cmp(b), Some(Ordering::Equal));
            assert_ne!(b.partial_cmp(a), Some(Ordering::Equal));
        }

        /// Edge 0-2: str vs Box<str>
        #[test]
        fn e02_str_vs_box_str() {
            let b = box_mk(B);
            assert_ne!(A, b);
            assert_ne!(b, A);
            assert!(!A.eq(&b));
            assert!(!b.eq(A));
            assert_ne!(A.partial_cmp(&b), Some(Ordering::Equal));
            assert_ne!(b.partial_cmp(A), Some(Ordering::Equal));
        }

        /// Edge 0-3: str vs String
        #[test]
        fn e03_str_vs_string() {
            let s = mk(B);
            assert_ne!(A, s);
            assert_ne!(s, A);
            assert!(!A.eq(&s));
            assert!(!s.eq(A));
            assert_ne!(A.partial_cmp(&s), Some(Ordering::Equal));
            assert_ne!(s.partial_cmp(A), Some(Ordering::Equal));
        }

        /// Edge 0-4: str vs Cow::Borrowed
        #[test]
        fn e04_str_vs_cow_borrowed() {
            let c: Cow<str> = Cow::Borrowed(B);
            assert_ne!(A, c);
            assert_ne!(c, A);
            assert!(!A.eq(&c));
            assert!(!c.eq(A));
            assert_ne!(A.partial_cmp(&c), Some(Ordering::Equal));
            assert_ne!(c.partial_cmp(A), Some(Ordering::Equal));
        }

        /// Edge 0-5: str vs Cow::Owned
        #[test]
        fn e05_str_vs_cow_owned() {
            let c: Cow<str> = Cow::Owned(mk(B));
            assert_ne!(A, c);
            assert_ne!(c, A);
            assert!(!A.eq(&c));
            assert!(!c.eq(A));
            assert_ne!(A.partial_cmp(&c), Some(Ordering::Equal));
            assert_ne!(c.partial_cmp(A), Some(Ordering::Equal));
        }

        /// Edge 1-2: &str vs Box<str>
        #[test]
        fn e12_ref_str_vs_box_str() {
            let r: &str = A;
            let b = box_mk(B);
            assert_ne!(r, b);
            assert_ne!(b, r);
            assert!(!r.eq(&b));
            assert!(!b.eq(r));
            assert_ne!(r.partial_cmp(&b), Some(Ordering::Equal));
            assert_ne!(b.partial_cmp(r), Some(Ordering::Equal));
        }

        /// Edge 1-3: &str vs String
        #[test]
        fn e13_ref_str_vs_string() {
            let r: &str = A;
            let s = mk(B);
            assert_ne!(r, s);
            assert_ne!(s, r);
            assert!(!r.eq(&s));
            assert!(!s.eq(r));
            assert_ne!(r.partial_cmp(&s), Some(Ordering::Equal));
            assert_ne!(s.partial_cmp(r), Some(Ordering::Equal));
        }

        /// Edge 1-4: &str vs Cow::Borrowed
        #[test]
        fn e14_ref_str_vs_cow_borrowed() {
            let r: &str = A;
            let c: Cow<str> = Cow::Borrowed(B);
            assert_ne!(r, c);
            assert_ne!(c, r);
            assert!(!r.eq(&c));
            assert!(!c.eq(r));
            assert_ne!(r.partial_cmp(&c), Some(Ordering::Equal));
            assert_ne!(c.partial_cmp(r), Some(Ordering::Equal));
        }

        /// Edge 1-5: &str vs Cow::Owned
        #[test]
        fn e15_ref_str_vs_cow_owned() {
            let r: &str = A;
            let c: Cow<str> = Cow::Owned(mk(B));
            assert_ne!(r, c);
            assert_ne!(c, r);
            assert!(!r.eq(&c));
            assert!(!c.eq(r));
            assert_ne!(r.partial_cmp(&c), Some(Ordering::Equal));
            assert_ne!(c.partial_cmp(r), Some(Ordering::Equal));
        }

        /// Edge 2-3: Box<str> vs String
        #[test]
        fn e23_box_str_vs_string() {
            let b = box_mk(A);
            let s = mk(B);
            assert_ne!(b, s);
            assert_ne!(s, b);
            assert!(!b.eq(&s));
            assert!(!s.eq(&b));
            assert_ne!(b.partial_cmp(&s), Some(Ordering::Equal));
            assert_ne!(s.partial_cmp(&b), Some(Ordering::Equal));
        }

        /// Edge 2-4: Box<str> vs Cow::Borrowed
        #[test]
        fn e24_box_str_vs_cow_borrowed() {
            let b = box_mk(A);
            let c: Cow<str> = Cow::Borrowed(B);
            assert_ne!(b, c);
            assert_ne!(c, b);
            assert!(!b.eq(&c));
            assert!(!c.eq(&b));
            assert_ne!(b.partial_cmp(&c), Some(Ordering::Equal));
            assert_ne!(c.partial_cmp(&b), Some(Ordering::Equal));
        }

        /// Edge 2-5: Box<str> vs Cow::Owned
        #[test]
        fn e25_box_str_vs_cow_owned() {
            let b = box_mk(A);
            let c: Cow<str> = Cow::Owned(mk(B));
            assert_ne!(b, c);
            assert_ne!(c, b);
            assert!(!b.eq(&c));
            assert!(!c.eq(&b));
            assert_ne!(b.partial_cmp(&c), Some(Ordering::Equal));
            assert_ne!(c.partial_cmp(&b), Some(Ordering::Equal));
        }

        /// Edge 3-4: String vs Cow::Borrowed
        #[test]
        fn e34_string_vs_cow_borrowed() {
            let s = mk(A);
            let c: Cow<str> = Cow::Borrowed(B);
            assert_ne!(s, c);
            assert_ne!(c, s);
            assert!(!s.eq(&c));
            assert!(!c.eq(&s));
            assert_ne!(s.partial_cmp(&c), Some(Ordering::Equal));
            assert_ne!(c.partial_cmp(&s), Some(Ordering::Equal));
        }

        /// Edge 3-5: String vs Cow::Owned
        #[test]
        fn e35_string_vs_cow_owned() {
            let s = mk(A);
            let c: Cow<str> = Cow::Owned(mk(B));
            assert_ne!(s, c);
            assert_ne!(c, s);
            assert!(!s.eq(&c));
            assert!(!c.eq(&s));
            assert_ne!(s.partial_cmp(&c), Some(Ordering::Equal));
            assert_ne!(c.partial_cmp(&s), Some(Ordering::Equal));
        }

        /// Edge 4-5: Cow::Borrowed vs Cow::Owned
        #[test]
        fn e45_cow_borrowed_vs_cow_owned() {
            let cb: Cow<str> = Cow::Borrowed(A);
            let co: Cow<str> = Cow::Owned(mk(B));
            assert_ne!(cb, co);
            assert_ne!(co, cb);
            assert!(!cb.eq(&co));
            assert!(!co.eq(&cb));
            assert_ne!(cb.partial_cmp(&co), Some(Ordering::Equal));
            assert_ne!(co.partial_cmp(&cb), Some(Ordering::Equal));
        }
    }

    // ───────────────────────────────────────────────────────────────────────
    // BATCH 3: Strictly-increasing ordering (transitivity + duality)
    // Three values LO < MID < HI. For each edge (X, Y):
    //   • X_LO.partial_cmp(Y_MID) == Less,  Y_MID.partial_cmp(X_HI) == Greater
    //     (directional correctness)
    //   • X_LO.partial_cmp(Y_HI) == Less    (transitivity: LO<MID, MID<HI ⇒ LO<HI)
    //   • Flipping operands dualises: Less ↔ Greater
    // ───────────────────────────────────────────────────────────────────────

    mod batch3_ordering {
        use super::*;

        // Shared suffix " café" (includes 2-byte é); differ only in the
        // leading astral-plane emoji (4 bytes each):
        //   😀 U+1F600 < 😁 U+1F601 < 😂 U+1F602
        const LO: &str = "\u{1F600} café";
        const MID: &str = "\u{1F601} café";
        const HI: &str = "\u{1F602} café";

        /// Edge 0-1: str vs &str
        #[test]
        fn e01_str_vs_ref_str() {
            let lo: &str = LO;
            let mid: &str = MID;
            let hi: &str = HI;
            assert_eq!(lo.partial_cmp(mid), Some(Ordering::Less));
            assert_eq!(mid.partial_cmp(hi), Some(Ordering::Less));
            assert_eq!(lo.partial_cmp(hi), Some(Ordering::Less)); // transitivity
            // Duality
            assert_eq!(mid.partial_cmp(lo), Some(Ordering::Greater));
            assert_eq!(hi.partial_cmp(mid), Some(Ordering::Greater));
            assert_eq!(hi.partial_cmp(lo), Some(Ordering::Greater));
        }

        /// Edge 0-2: str vs Box<str>
        #[test]
        fn e02_str_vs_box_str() {
            let lo: &str = LO;
            let mid_box = box_mk(MID);
            let hi_box = box_mk(HI);
            assert_eq!(lo.partial_cmp(&mid_box), Some(Ordering::Less));
            assert_eq!(mid_box.partial_cmp(&hi_box), Some(Ordering::Less));
            assert_eq!(lo.partial_cmp(&hi_box), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_box.partial_cmp(lo), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(&mid_box), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(lo), Some(Ordering::Greater));
        }

        /// Edge 0-3: str vs String
        #[test]
        fn e03_str_vs_string() {
            let lo: &str = LO;
            let mid_s = mk(MID);
            let hi_s = mk(HI);
            assert_eq!(lo.partial_cmp(&mid_s), Some(Ordering::Less));
            assert_eq!(mid_s.partial_cmp(&hi_s), Some(Ordering::Less));
            assert_eq!(lo.partial_cmp(&hi_s), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_s.partial_cmp(lo), Some(Ordering::Greater));
            assert_eq!(hi_s.partial_cmp(&mid_s), Some(Ordering::Greater));
            assert_eq!(hi_s.partial_cmp(lo), Some(Ordering::Greater));
        }

        /// Edge 0-4: str vs Cow::Borrowed
        #[test]
        fn e04_str_vs_cow_borrowed() {
            let lo: &str = LO;
            let mid_c: Cow<str> = Cow::Borrowed(MID);
            let hi_c: Cow<str> = Cow::Borrowed(HI);
            assert_eq!(lo.partial_cmp(&mid_c), Some(Ordering::Less));
            assert_eq!(mid_c.partial_cmp(&hi_c), Some(Ordering::Less));
            assert_eq!(lo.partial_cmp(&hi_c), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_c.partial_cmp(lo), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(&mid_c), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(lo), Some(Ordering::Greater));
        }

        /// Edge 0-5: str vs Cow::Owned
        #[test]
        fn e05_str_vs_cow_owned() {
            let lo: &str = LO;
            let mid_c: Cow<str> = Cow::Owned(mk(MID));
            let hi_c: Cow<str> = Cow::Owned(mk(HI));
            assert_eq!(lo.partial_cmp(&mid_c), Some(Ordering::Less));
            assert_eq!(mid_c.partial_cmp(&hi_c), Some(Ordering::Less));
            assert_eq!(lo.partial_cmp(&hi_c), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_c.partial_cmp(lo), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(&mid_c), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(lo), Some(Ordering::Greater));
        }

        /// Edge 1-2: &str vs Box<str>
        #[test]
        fn e12_ref_str_vs_box_str() {
            let lo: &str = LO;
            let mid_box = box_mk(MID);
            let hi_box = box_mk(HI);
            assert_eq!(lo.partial_cmp(&mid_box), Some(Ordering::Less));
            assert_eq!(mid_box.partial_cmp(&hi_box), Some(Ordering::Less));
            assert_eq!(lo.partial_cmp(&hi_box), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_box.partial_cmp(lo), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(&mid_box), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(lo), Some(Ordering::Greater));
        }

        /// Edge 1-3: &str vs String
        #[test]
        fn e13_ref_str_vs_string() {
            let lo: &str = LO;
            let mid_s = mk(MID);
            let hi_s = mk(HI);
            assert_eq!(lo.partial_cmp(&mid_s), Some(Ordering::Less));
            assert_eq!(mid_s.partial_cmp(&hi_s), Some(Ordering::Less));
            assert_eq!(lo.partial_cmp(&hi_s), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_s.partial_cmp(lo), Some(Ordering::Greater));
            assert_eq!(hi_s.partial_cmp(&mid_s), Some(Ordering::Greater));
            assert_eq!(hi_s.partial_cmp(lo), Some(Ordering::Greater));
        }

        /// Edge 1-4: &str vs Cow::Borrowed
        #[test]
        fn e14_ref_str_vs_cow_borrowed() {
            let lo: &str = LO;
            let mid_c: Cow<str> = Cow::Borrowed(MID);
            let hi_c: Cow<str> = Cow::Borrowed(HI);
            assert_eq!(lo.partial_cmp(&mid_c), Some(Ordering::Less));
            assert_eq!(mid_c.partial_cmp(&hi_c), Some(Ordering::Less));
            assert_eq!(lo.partial_cmp(&hi_c), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_c.partial_cmp(lo), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(&mid_c), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(lo), Some(Ordering::Greater));
        }

        /// Edge 1-5: &str vs Cow::Owned
        #[test]
        fn e15_ref_str_vs_cow_owned() {
            let lo: &str = LO;
            let mid_c: Cow<str> = Cow::Owned(mk(MID));
            let hi_c: Cow<str> = Cow::Owned(mk(HI));
            assert_eq!(lo.partial_cmp(&mid_c), Some(Ordering::Less));
            assert_eq!(mid_c.partial_cmp(&hi_c), Some(Ordering::Less));
            assert_eq!(lo.partial_cmp(&hi_c), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_c.partial_cmp(lo), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(&mid_c), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(lo), Some(Ordering::Greater));
        }

        /// Edge 2-3: Box<str> vs String
        #[test]
        fn e23_box_str_vs_string() {
            let lo_box = box_mk(LO);
            let mid_s = mk(MID);
            let hi_box = box_mk(HI);
            assert_eq!(lo_box.partial_cmp(&mid_s), Some(Ordering::Less));
            assert_eq!(mid_s.partial_cmp(&hi_box), Some(Ordering::Less));
            assert_eq!(lo_box.partial_cmp(&hi_box), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_s.partial_cmp(&lo_box), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(&mid_s), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(&lo_box), Some(Ordering::Greater));
        }

        /// Edge 2-4: Box<str> vs Cow::Borrowed
        #[test]
        fn e24_box_str_vs_cow_borrowed() {
            let lo_box = box_mk(LO);
            let mid_c: Cow<str> = Cow::Borrowed(MID);
            let hi_box = box_mk(HI);
            assert_eq!(lo_box.partial_cmp(&mid_c), Some(Ordering::Less));
            assert_eq!(mid_c.partial_cmp(&hi_box), Some(Ordering::Less));
            assert_eq!(lo_box.partial_cmp(&hi_box), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_c.partial_cmp(&lo_box), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(&mid_c), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(&lo_box), Some(Ordering::Greater));
        }

        /// Edge 2-5: Box<str> vs Cow::Owned
        #[test]
        fn e25_box_str_vs_cow_owned() {
            let lo_box = box_mk(LO);
            let mid_c: Cow<str> = Cow::Owned(mk(MID));
            let hi_box = box_mk(HI);
            assert_eq!(lo_box.partial_cmp(&mid_c), Some(Ordering::Less));
            assert_eq!(mid_c.partial_cmp(&hi_box), Some(Ordering::Less));
            assert_eq!(lo_box.partial_cmp(&hi_box), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_c.partial_cmp(&lo_box), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(&mid_c), Some(Ordering::Greater));
            assert_eq!(hi_box.partial_cmp(&lo_box), Some(Ordering::Greater));
        }

        /// Edge 3-4: String vs Cow::Borrowed
        #[test]
        fn e34_string_vs_cow_borrowed() {
            let lo_s = mk(LO);
            let mid_c: Cow<str> = Cow::Borrowed(MID);
            let hi_s = mk(HI);
            assert_eq!(lo_s.partial_cmp(&mid_c), Some(Ordering::Less));
            assert_eq!(mid_c.partial_cmp(&hi_s), Some(Ordering::Less));
            assert_eq!(lo_s.partial_cmp(&hi_s), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_c.partial_cmp(&lo_s), Some(Ordering::Greater));
            assert_eq!(hi_s.partial_cmp(&mid_c), Some(Ordering::Greater));
            assert_eq!(hi_s.partial_cmp(&lo_s), Some(Ordering::Greater));
        }

        /// Edge 3-5: String vs Cow::Owned
        #[test]
        fn e35_string_vs_cow_owned() {
            let lo_s = mk(LO);
            let mid_c: Cow<str> = Cow::Owned(mk(MID));
            let hi_s = mk(HI);
            assert_eq!(lo_s.partial_cmp(&mid_c), Some(Ordering::Less));
            assert_eq!(mid_c.partial_cmp(&hi_s), Some(Ordering::Less));
            assert_eq!(lo_s.partial_cmp(&hi_s), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_c.partial_cmp(&lo_s), Some(Ordering::Greater));
            assert_eq!(hi_s.partial_cmp(&mid_c), Some(Ordering::Greater));
            assert_eq!(hi_s.partial_cmp(&lo_s), Some(Ordering::Greater));
        }

        /// Edge 4-5: Cow::Borrowed vs Cow::Owned
        #[test]
        fn e45_cow_borrowed_vs_cow_owned() {
            let lo_c: Cow<str> = Cow::Borrowed(LO);
            let mid_c: Cow<str> = Cow::Owned(mk(MID));
            let hi_c: Cow<str> = Cow::Borrowed(HI);
            assert_eq!(lo_c.partial_cmp(&mid_c), Some(Ordering::Less));
            assert_eq!(mid_c.partial_cmp(&hi_c), Some(Ordering::Less));
            assert_eq!(lo_c.partial_cmp(&hi_c), Some(Ordering::Less));
            // Duality
            assert_eq!(mid_c.partial_cmp(&lo_c), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(&mid_c), Some(Ordering::Greater));
            assert_eq!(hi_c.partial_cmp(&lo_c), Some(Ordering::Greater));
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    // BATCH 4: Full-network transitivity (ascending hierarchy)
    // Assign each of the 6 representations a distinct rank from a strictly
    // increasing sequence V0 < V1 < V2 < V3 < V4 < V5. Verify that for every
    // ordered pair (i, j) with i < j, the comparison yields Less, and its
    // dual `j > i` yields Greater — both asserted within the same test.
    // Since all C(6,2)=15 pairs are checked, transitivity across any subset
    // of adjacent hops is implied by the local edges already verified.
    //
    // Rank assignment (strictly ascending by codepoint):
    //   rank 0 → str            (V0 = "")
    //   rank 1 → &str           (V1 = "\t\n\r")
    //   rank 2 → Box<str>       (V2 = " ")
    //   rank 3 → String         (V3 = "héllo")
    //   rank 4 → Cow::Borrowed  (V4 = "héllo world")
    //   rank 5 → Cow::Owned     (V5 = "🌍 héllo world!")
    // ═══════════════════════════════════════════════════════════════════════

    mod batch4_network_transitivity_asc {
        use super::*;

        // Strictly ascending by codepoint order
        const V0: &str = ""; // str          (empty)
        const V1: &str = "\t\n\r"; // &str         (control chars)
        const V2: &str = " "; // Box<str>     (single space)
        const V3: &str = "héllo"; // String       (multibyte mid)
        const V4: &str = "héllo world"; // Cow::Borrowed (shared prefix, longer)
        const V5: &str = "🌍 héllo world!"; // Cow::Owned  (special char + longest)

        /// Build all six ranked values.
        struct Ranked {
            v0_str: &'static str,
            v1_ref: &'static str,
            v2_box: Box<str>,
            v3_string: String,
            v4_cow_b: Cow<'static, str>,
            v5_cow_o: Cow<'static, str>,
        }

        fn build() -> Ranked {
            Ranked {
                v0_str: V0,
                v1_ref: V1,
                v2_box: box_mk(V2),
                v3_string: mk(V3),
                v4_cow_b: Cow::Borrowed(V4),
                v5_cow_o: Cow::Owned(mk(V5)),
            }
        }

        /// Helper: assert `lhs.partial_cmp(rhs) == Some(Less)` and the dual.
        #[track_caller]
        fn assert_less(lhs_result: Option<Ordering>, rhs_result: Option<Ordering>, label: &str) {
            assert_eq!(lhs_result, Some(Ordering::Less), "{label}: expected Less");
            assert_eq!(
                rhs_result,
                Some(Ordering::Greater),
                "{label}: expected Greater (dual)"
            );
        }

        /// All C(6,2) = 15 pairs, ascending direction.
        #[test]
        fn all_pairs_ascending() {
            let r = build();

            // (0,1): str < &str
            assert_less(
                r.v0_str.partial_cmp(r.v1_ref),
                r.v1_ref.partial_cmp(r.v0_str),
                "V0(str) < V1(&str)",
            );

            // (0,2): str < Box<str>
            assert_less(
                r.v0_str.partial_cmp(&r.v2_box),
                r.v2_box.partial_cmp(r.v0_str),
                "V0(str) < V2(Box<str>)",
            );

            // (0,3): str < String
            assert_less(
                r.v0_str.partial_cmp(&r.v3_string),
                r.v3_string.partial_cmp(r.v0_str),
                "V0(str) < V3(String)",
            );

            // (0,4): str < Cow::Borrowed
            assert_less(
                r.v0_str.partial_cmp(&r.v4_cow_b),
                r.v4_cow_b.partial_cmp(r.v0_str),
                "V0(str) < V4(Cow::Borrowed)",
            );

            // (0,5): str < Cow::Owned
            assert_less(
                r.v0_str.partial_cmp(&r.v5_cow_o),
                r.v5_cow_o.partial_cmp(r.v0_str),
                "V0(str) < V5(Cow::Owned)",
            );

            // (1,2): &str < Box<str>
            assert_less(
                r.v1_ref.partial_cmp(&r.v2_box),
                r.v2_box.partial_cmp(r.v1_ref),
                "V1(&str) < V2(Box<str>)",
            );

            // (1,3): &str < String
            assert_less(
                r.v1_ref.partial_cmp(&r.v3_string),
                r.v3_string.partial_cmp(r.v1_ref),
                "V1(&str) < V3(String)",
            );

            // (1,4): &str < Cow::Borrowed
            assert_less(
                r.v1_ref.partial_cmp(&r.v4_cow_b),
                r.v4_cow_b.partial_cmp(r.v1_ref),
                "V1(&str) < V4(Cow::Borrowed)",
            );

            // (1,5): &str < Cow::Owned
            assert_less(
                r.v1_ref.partial_cmp(&r.v5_cow_o),
                r.v5_cow_o.partial_cmp(r.v1_ref),
                "V1(&str) < V5(Cow::Owned)",
            );

            // (2,3): Box<str> < String
            assert_less(
                r.v2_box.partial_cmp(&r.v3_string),
                r.v3_string.partial_cmp(&r.v2_box),
                "V2(Box<str>) < V3(String)",
            );

            // (2,4): Box<str> < Cow::Borrowed
            assert_less(
                r.v2_box.partial_cmp(&r.v4_cow_b),
                r.v4_cow_b.partial_cmp(&r.v2_box),
                "V2(Box<str>) < V4(Cow::Borrowed)",
            );

            // (2,5): Box<str> < Cow::Owned
            assert_less(
                r.v2_box.partial_cmp(&r.v5_cow_o),
                r.v5_cow_o.partial_cmp(&r.v2_box),
                "V2(Box<str>) < V5(Cow::Owned)",
            );

            // (3,4): String < Cow::Borrowed
            assert_less(
                r.v3_string.partial_cmp(&r.v4_cow_b),
                r.v4_cow_b.partial_cmp(&r.v3_string),
                "V3(String) < V4(Cow::Borrowed)",
            );

            // (3,5): String < Cow::Owned
            assert_less(
                r.v3_string.partial_cmp(&r.v5_cow_o),
                r.v5_cow_o.partial_cmp(&r.v3_string),
                "V3(String) < V5(Cow::Owned)",
            );

            // (4,5): Cow::Borrowed < Cow::Owned
            assert_less(
                r.v4_cow_b.partial_cmp(&r.v5_cow_o),
                r.v5_cow_o.partial_cmp(&r.v4_cow_b),
                "V4(Cow::Borrowed) < V5(Cow::Owned)",
            );
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    // BATCH 5: Full-network transitivity (descending hierarchy)
    // Independent complement to Batch 4: assigns the same six values but maps
    // them to representations in reverse order, so every cross-representation
    // pair now asserts Greater where Batch 4 asserted Less. Duality is checked
    // within each test (every `a > b` is paired with `b < a`).
    //
    // Rank assignment (same values as Batch 4, reversed representation mapping):
    //   rank 5 → str            (W5 = "🌍 héllo world!")
    //   rank 4 → &str           (W4 = "héllo world")
    //   rank 3 → Box<str>       (W3 = "héllo")
    //   rank 2 → String         (W2 = " ")
    //   rank 1 → Cow::Borrowed  (W1 = "\t\n\r")
    //   rank 0 → Cow::Owned     (W0 = "")
    // ═══════════════════════════════════════════════════════════════════════

    mod batch5_network_transitivity_desc {
        use super::*;

        // Same six values as Batch 4, assigned in reverse to representations:
        //   W0 < W1 < W2 < W3 < W4 < W5
        const W0: &str = ""; // Cow::Owned  (empty, lowest)
        const W1: &str = "\t\n\r"; // Cow::Borrowed
        const W2: &str = " "; // String
        const W3: &str = "héllo"; // Box<str>
        const W4: &str = "héllo world"; // &str
        const W5: &str = "🌍 héllo world!"; // str         (astral, highest)

        struct RankedDesc {
            w0_cow_o: Cow<'static, str>,
            w1_cow_b: Cow<'static, str>,
            w2_string: String,
            w3_box: Box<str>,
            w4_ref: &'static str,
            w5_str: &'static str,
        }

        fn build() -> RankedDesc {
            RankedDesc {
                w0_cow_o: Cow::Owned(mk(W0)),
                w1_cow_b: Cow::Borrowed(W1),
                w2_string: mk(W2),
                w3_box: box_mk(W3),
                w4_ref: W4,
                w5_str: W5,
            }
        }

        #[track_caller]
        fn assert_greater(lhs_result: Option<Ordering>, rhs_result: Option<Ordering>, label: &str) {
            assert_eq!(
                lhs_result,
                Some(Ordering::Greater),
                "{label}: expected Greater"
            );
            assert_eq!(
                rhs_result,
                Some(Ordering::Less),
                "{label}: expected Less (dual)"
            );
        }

        /// All C(6,2) = 15 pairs, descending direction (higher-rank rep > lower-rank rep).
        #[test]
        fn all_pairs_descending() {
            let r = build();

            // (5,4): str > &str
            assert_greater(
                r.w5_str.partial_cmp(r.w4_ref),
                r.w4_ref.partial_cmp(r.w5_str),
                "W5(str) > W4(&str)",
            );

            // (5,3): str > Box<str>
            assert_greater(
                r.w5_str.partial_cmp(&r.w3_box),
                r.w3_box.partial_cmp(r.w5_str),
                "W5(str) > W3(Box<str>)",
            );

            // (5,2): str > String
            assert_greater(
                r.w5_str.partial_cmp(&r.w2_string),
                r.w2_string.partial_cmp(r.w5_str),
                "W5(str) > W2(String)",
            );

            // (5,1): str > Cow::Borrowed
            assert_greater(
                r.w5_str.partial_cmp(&r.w1_cow_b),
                r.w1_cow_b.partial_cmp(r.w5_str),
                "W5(str) > W1(Cow::Borrowed)",
            );

            // (5,0): str > Cow::Owned
            assert_greater(
                r.w5_str.partial_cmp(&r.w0_cow_o),
                r.w0_cow_o.partial_cmp(r.w5_str),
                "W5(str) > W0(Cow::Owned)",
            );

            // (4,3): &str > Box<str>
            assert_greater(
                r.w4_ref.partial_cmp(&r.w3_box),
                r.w3_box.partial_cmp(r.w4_ref),
                "W4(&str) > W3(Box<str>)",
            );

            // (4,2): &str > String
            assert_greater(
                r.w4_ref.partial_cmp(&r.w2_string),
                r.w2_string.partial_cmp(r.w4_ref),
                "W4(&str) > W2(String)",
            );

            // (4,1): &str > Cow::Borrowed
            assert_greater(
                r.w4_ref.partial_cmp(&r.w1_cow_b),
                r.w1_cow_b.partial_cmp(r.w4_ref),
                "W4(&str) > W1(Cow::Borrowed)",
            );

            // (4,0): &str > Cow::Owned
            assert_greater(
                r.w4_ref.partial_cmp(&r.w0_cow_o),
                r.w0_cow_o.partial_cmp(r.w4_ref),
                "W4(&str) > W0(Cow::Owned)",
            );

            // (3,2): Box<str> > String
            assert_greater(
                r.w3_box.partial_cmp(&r.w2_string),
                r.w2_string.partial_cmp(&r.w3_box),
                "W3(Box<str>) > W2(String)",
            );

            // (3,1): Box<str> > Cow::Borrowed
            assert_greater(
                r.w3_box.partial_cmp(&r.w1_cow_b),
                r.w1_cow_b.partial_cmp(&r.w3_box),
                "W3(Box<str>) > W1(Cow::Borrowed)",
            );

            // (3,0): Box<str> > Cow::Owned
            assert_greater(
                r.w3_box.partial_cmp(&r.w0_cow_o),
                r.w0_cow_o.partial_cmp(&r.w3_box),
                "W3(Box<str>) > W0(Cow::Owned)",
            );

            // (2,1): String > Cow::Borrowed
            assert_greater(
                r.w2_string.partial_cmp(&r.w1_cow_b),
                r.w1_cow_b.partial_cmp(&r.w2_string),
                "W2(String) > W1(Cow::Borrowed)",
            );

            // (2,0): String > Cow::Owned
            assert_greater(
                r.w2_string.partial_cmp(&r.w0_cow_o),
                r.w0_cow_o.partial_cmp(&r.w2_string),
                "W2(String) > W0(Cow::Owned)",
            );

            // (1,0): Cow::Borrowed > Cow::Owned
            assert_greater(
                r.w1_cow_b.partial_cmp(&r.w0_cow_o),
                r.w0_cow_o.partial_cmp(&r.w1_cow_b),
                "W1(Cow::Borrowed) > W0(Cow::Owned)",
            );
        }
    }

    // ───────────────────────────────────────────────────────────────────────
    // Allocator-genericity: comparisons must be content-only regardless of
    // which allocator backs the String.
    // ───────────────────────────────────────────────────────────────────────

    #[test]
    fn cmp_generic_over_allocator() {
        use crate::alloc::CountingAllocator;
        type CA = CountingAllocator;
        type S = String<CA>;

        // Combines 2-byte accent (é), 4-byte astral (😀), and ASCII.
        let content = "héllo \u{1F600} foreign";
        let s = S::try_from_str_in(content, CA::new()).unwrap();

        assert_eq!(s, content);
        assert_eq!(content, s);
        assert_ne!(s, "héllo \u{1F601} foreign");
        assert_eq!(s.partial_cmp(content), Some(Ordering::Equal));
        assert_eq!(
            s.partial_cmp("\u{1F601} héllo foreign"),
            Some(Ordering::Less)
        );

        let r: &str = content;
        assert_eq!(s, r);
        assert_eq!(r, s);
        assert_eq!(s.partial_cmp(r), Some(Ordering::Equal));

        let b: Box<str> = Box::try_clone_from_ref(content).unwrap();
        assert_eq!(s, b);
        assert_eq!(b, s);
        assert_eq!(s.partial_cmp(&b), Some(Ordering::Equal));

        let rb: &Box<str> = &b;
        assert_eq!(s, rb);
        assert_eq!(rb, s);
        assert_eq!(s.partial_cmp(rb), Some(Ordering::Equal));
    }
}
